// <auto-generated />
using System;
using DevWeb_Trab_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevWeb_Trab_Final.Migrations
{
    [DbContext(typeof(DevWeb_Trab_FinalContext))]
    [Migration("20230710145045_InserirUtilizadoresFinal")]
    partial class InserirUtilizadoresFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevWeb_Trab_Final.Data.DevWeb_Trab_Final_User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeUtilizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "defaa072-55ae-4469-abd6-a3edc1449072",
                            DataRegisto = new DateTime(2023, 1, 1, 9, 0, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "administrador_1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Administrador UM",
                            NormalizedEmail = "ADMINISTRADOR_1@GMAIL.COM",
                            NormalizedUserName = "ADMINISTRADOR_1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b78d352d-7344-4826-b37e-d7516096e553",
                            TwoFactorEnabled = false,
                            UserName = "administrador_1@gmail.com"
                        },
                        new
                        {
                            Id = "a2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6599ef3-172c-41c7-abb0-98072a154fc7",
                            DataRegisto = new DateTime(2023, 1, 1, 9, 0, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "administrador_2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Administrador DOIS",
                            NormalizedEmail = "ADMINISTRADOR_2@GMAIL.COM",
                            NormalizedUserName = "ADMINISTRADOR_2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c41c3ea7-3de1-475d-8e08-a766e813b837",
                            TwoFactorEnabled = false,
                            UserName = "administrador_2@gmail.com"
                        },
                        new
                        {
                            Id = "f1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4be2b8b8-5007-4b21-a0bb-14e10ce98099",
                            DataRegisto = new DateTime(2023, 1, 20, 11, 0, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "daniel@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Daniel Filipe",
                            NormalizedEmail = "DANIEL@GMAIL.COM",
                            NormalizedUserName = "DANIEL@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "912123123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f358514-896a-4544-9da5-afd44f501cb2",
                            TwoFactorEnabled = false,
                            UserName = "daniel@gmail.com"
                        },
                        new
                        {
                            Id = "f2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7648c2b1-304c-4baa-8c99-8e084bc2cc0c",
                            DataRegisto = new DateTime(2023, 1, 15, 14, 20, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "rodrigo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Rodrigo Antunes",
                            NormalizedEmail = "RODRIGO@GMAIL.COM",
                            NormalizedUserName = "RODRIGO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "915789789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d3a3bb8-ee17-4b77-b060-8b8a4ecb8444",
                            TwoFactorEnabled = false,
                            UserName = "rodrigo@gmail.com"
                        },
                        new
                        {
                            Id = "f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c032d3f3-4b09-4bc6-9d31-7d2bfc3979e4",
                            DataRegisto = new DateTime(2023, 1, 29, 16, 0, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "leia.marques@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Leia Marques",
                            NormalizedEmail = "LEIA.MARQUES@GMAIL.COM",
                            NormalizedUserName = "LEIA.MARQUES@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "962231123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b682ffc1-1b00-4170-98c6-c8c72ec55807",
                            TwoFactorEnabled = false,
                            UserName = "leia.marques@gmail.com"
                        },
                        new
                        {
                            Id = "f4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "42f5964a-446d-49cd-b402-03664b4081d5",
                            DataRegisto = new DateTime(2023, 2, 2, 12, 15, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "carlos@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Carlos Tomaz",
                            NormalizedEmail = "CARLOS@GMAIL.COM",
                            NormalizedUserName = "CARLOS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "932553923",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "569cf23b-ce85-41f9-ac1e-79a26d23cff8",
                            TwoFactorEnabled = false,
                            UserName = "carlos@gmail.com"
                        },
                        new
                        {
                            Id = "f5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39be2b4a-685f-42e9-95e5-c8bf1e048ce7",
                            DataRegisto = new DateTime(2023, 2, 18, 11, 50, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "tiago_varandas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Tiago Roberto Varandas",
                            NormalizedEmail = "TIAGO_VARANDAS@GMAIL.COM",
                            NormalizedUserName = "TIAGO_VARANDAS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "922456123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1d32542-5de4-4d6b-b622-c46479ad03da",
                            TwoFactorEnabled = false,
                            UserName = "tiago_varandas@gmail.com"
                        },
                        new
                        {
                            Id = "c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72c4ef58-65f2-41f0-970d-b549564447ca",
                            DataRegisto = new DateTime(2023, 2, 13, 14, 10, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "alberto@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Alberto Santos",
                            NormalizedEmail = "ALBERTO@HOTMAIL.COM",
                            NormalizedUserName = "ALBERTO@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "969777666",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8314899-0afc-4289-8677-ca3798c30543",
                            TwoFactorEnabled = false,
                            UserName = "alberto@hotmail.com"
                        },
                        new
                        {
                            Id = "c2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c7e0ff0-3fa6-4fff-988c-0339c69d9412",
                            DataRegisto = new DateTime(2023, 5, 9, 17, 59, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "maria.joao@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Maria João",
                            NormalizedEmail = "MARIA.JOAO@HOTMAIL.COM",
                            NormalizedUserName = "MARIA.JOAO@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "933751916",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01fa1f1a-c62e-4ffb-8d79-0df481c16b96",
                            TwoFactorEnabled = false,
                            UserName = "maria.joao@hotmail.com"
                        },
                        new
                        {
                            Id = "c3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12fb0a08-b963-40f8-a74c-33ca8d535f36",
                            DataRegisto = new DateTime(2023, 6, 23, 12, 40, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "catarina@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Catarina Moedas",
                            NormalizedEmail = "CATARINA@HOTMAIL.COM",
                            NormalizedUserName = "CATARINA@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "919744531",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "785aacae-a247-4bd6-a87d-4a605eac16c5",
                            TwoFactorEnabled = false,
                            UserName = "catarina@hotmail.com"
                        },
                        new
                        {
                            Id = "c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9433725-7316-430d-bff8-304a6a53d519",
                            DataRegisto = new DateTime(2023, 3, 30, 9, 30, 0, 435, DateTimeKind.Local).AddTicks(8516),
                            Email = "gustavo_pal@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NomeUtilizador = "Gustavo Palhinha",
                            NormalizedEmail = "GUSTAVO_PAL@HOTMAIL.COM",
                            NormalizedUserName = "GUSTAVO_PAL@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDOPtP55I+lMq1ehxtZ/Rpmf9hZyZcdhNz6ZpUYOlbiXbGMZyjmx73VNO3dIUE6UQ==",
                            PhoneNumber = "923321348",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f9187d2-36af-43b6-9d86-5412b33bf26c",
                            TwoFactorEnabled = false,
                            UserName = "gustavo_pal@hotmail.com"
                        });
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NIF")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodPostal = "2500-654 PORTIMÃO",
                            Email = "alberto@hotmail.com",
                            Morada = "Bairo Rui Lopes",
                            NIF = 249249249,
                            Nome = "Alberto Santos",
                            Telemovel = "969777666",
                            UserId = "c1"
                        },
                        new
                        {
                            Id = 2,
                            CodPostal = "2678-283 LISBOA",
                            Email = "maria.joao@hotmail.com",
                            Morada = "Canto da Cerejeiras",
                            NIF = 256249999,
                            Nome = "Maria João",
                            Telemovel = "933751916",
                            UserId = "c2"
                        },
                        new
                        {
                            Id = 3,
                            CodPostal = "1672-123 AVEIRO",
                            Email = "catarina@hotmail.com",
                            Morada = "Rua Salvador Sobral",
                            NIF = 189234831,
                            Nome = "Catarina Moedas",
                            Telemovel = "919744531",
                            UserId = "c3"
                        },
                        new
                        {
                            Id = 4,
                            CodPostal = "3111-879 CASAIS",
                            Email = "gustavo_pal@hotmail.com",
                            Morada = "Placeta dos Santos Simões",
                            NIF = 222738901,
                            Nome = "Gustavo Palhinha",
                            Telemovel = "923321348",
                            UserId = "c4"
                        });
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Dispositivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFK");

                    b.ToTable("Dispositivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteFK = 1,
                            DataReg = new DateTime(2023, 2, 13, 14, 20, 48, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Ecrã Partido",
                            Modelo = "Asus",
                            Tipo = "PC-Alberto"
                        },
                        new
                        {
                            Id = 2,
                            ClienteFK = 2,
                            DataReg = new DateTime(2023, 5, 9, 18, 10, 14, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Não liga",
                            Modelo = "Samsung",
                            Tipo = "MicroOndas-Maria"
                        },
                        new
                        {
                            Id = 3,
                            ClienteFK = 2,
                            DataReg = new DateTime(2023, 7, 10, 15, 50, 45, 32, DateTimeKind.Local).AddTicks(7445),
                            Estado = "Não faz chamadas",
                            Modelo = "Xiaomi",
                            Tipo = "Telemovel-Maria"
                        },
                        new
                        {
                            Id = 4,
                            ClienteFK = 3,
                            DataReg = new DateTime(2023, 6, 23, 12, 50, 22, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Tem virus",
                            Modelo = "Apple",
                            Tipo = "Tablet-Catarina"
                        },
                        new
                        {
                            Id = 5,
                            ClienteFK = 4,
                            DataReg = new DateTime(2023, 3, 30, 9, 35, 34, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Não deixa mudar as horas",
                            Modelo = "Sony",
                            Tipo = "Relogio-Gustavo"
                        },
                        new
                        {
                            Id = 6,
                            ClienteFK = 4,
                            DataReg = new DateTime(2023, 7, 9, 14, 55, 44, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Bateria quase a rebentar",
                            Modelo = "HP",
                            Tipo = "Portatil-Gustavo"
                        },
                        new
                        {
                            Id = 7,
                            ClienteFK = 1,
                            DataReg = new DateTime(2023, 4, 4, 10, 20, 33, 435, DateTimeKind.Local).AddTicks(8516),
                            Estado = "Não vira",
                            Modelo = "Wahson",
                            Tipo = "Ventoinha-Alberto"
                        });
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Fotografias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DispositivoFK")
                        .HasColumnType("int");

                    b.Property<string>("NomeFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoFK");

                    b.ToTable("Fotografias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispositivoFK = 1,
                            NomeFoto = "noDispositivo.png"
                        },
                        new
                        {
                            Id = 2,
                            DispositivoFK = 2,
                            NomeFoto = "noDispositivo.png"
                        },
                        new
                        {
                            Id = 3,
                            DispositivoFK = 3,
                            NomeFoto = "noDispositivo.png"
                        },
                        new
                        {
                            Id = 4,
                            DispositivoFK = 4,
                            NomeFoto = "ipad.png"
                        },
                        new
                        {
                            Id = 5,
                            DispositivoFK = 5,
                            NomeFoto = "relogio.png"
                        },
                        new
                        {
                            Id = 6,
                            DispositivoFK = 6,
                            NomeFoto = "noDispositivo.png"
                        },
                        new
                        {
                            Id = 7,
                            DispositivoFK = 7,
                            NomeFoto = "ventoinha.png"
                        });
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Funcionarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Especializacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodPostal = "2300-450 TRAMAGAL",
                            Email = "daniel@gmail.com",
                            Especializacao = "Computadores",
                            Morada = "Rua da Pedrada",
                            Nome = "Daniel Filipe",
                            Telemovel = "912123123",
                            UserId = "f1"
                        },
                        new
                        {
                            Id = 2,
                            CodPostal = "2305-670 ALBUFEIRA",
                            Email = "rodrigo@gmail.com",
                            Especializacao = "Computadores",
                            Morada = "Rua do Pinheiro",
                            Nome = "Rodrigo Antunes",
                            Telemovel = "915789789",
                            UserId = "f2"
                        },
                        new
                        {
                            Id = 3,
                            CodPostal = "2200-301 BRAGA",
                            Email = "leia.marques@gmail.com",
                            Especializacao = "Telemóveis",
                            Morada = "Avenida 31 de Outubro",
                            Nome = "Leia Marques",
                            Telemovel = "962231123",
                            UserId = "f3"
                        },
                        new
                        {
                            Id = 4,
                            CodPostal = "2731-659 BEJA",
                            Email = "carlos@gmail.com",
                            Especializacao = "Eletrodomésticos",
                            Morada = "Praça da Nogueira",
                            Nome = "Carlos Tomaz",
                            Telemovel = "932553923",
                            UserId = "f4"
                        },
                        new
                        {
                            Id = 5,
                            CodPostal = "3030-155 SAGRES",
                            Email = "tiago_varandas@gmail.com",
                            Especializacao = "Tablets",
                            Morada = "Praia de Lagos",
                            Nome = "Tiago Roberto Varandas",
                            Telemovel = "922456123",
                            UserId = "f5"
                        });
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Reparacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispositivoFK")
                        .HasColumnType("int");

                    b.Property<int>("FuncionariosFK")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoFK");

                    b.HasIndex("FuncionariosFK");

                    b.ToTable("Reparacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Custo = 80.35m,
                            DataInicio = new DateTime(2023, 7, 10, 15, 50, 45, 32, DateTimeKind.Local).AddTicks(7559),
                            DispositivoFK = 1,
                            FuncionariosFK = 1,
                            Observacao = "É preciso comprar um ecrã novo"
                        },
                        new
                        {
                            Id = 2,
                            Custo = 50.43m,
                            DataInicio = new DateTime(2023, 5, 9, 18, 15, 44, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 2,
                            FuncionariosFK = 2,
                            Observacao = "É preciso trocar a fonte de alimentação"
                        },
                        new
                        {
                            Id = 3,
                            Custo = 7.52m,
                            DataInicio = new DateTime(2023, 5, 10, 19, 55, 59, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 2,
                            FuncionariosFK = 4,
                            Observacao = "É tambem preciso arranjar o cabo de alimentação"
                        },
                        new
                        {
                            Id = 4,
                            Custo = 10.67m,
                            DataInicio = new DateTime(2023, 7, 10, 15, 50, 45, 33, DateTimeKind.Local).AddTicks(8),
                            DispositivoFK = 3,
                            FuncionariosFK = 4,
                            Observacao = "É preciso mudar a antena"
                        },
                        new
                        {
                            Id = 5,
                            Custo = 20.20m,
                            DataInicio = new DateTime(2023, 6, 24, 11, 28, 23, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 4,
                            FuncionariosFK = 3,
                            Observacao = "Tentar meter um antivírus"
                        },
                        new
                        {
                            Id = 6,
                            Custo = 40.00m,
                            DataInicio = new DateTime(2023, 6, 25, 18, 48, 24, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 4,
                            FuncionariosFK = 5,
                            Observacao = "É preciso formatar o tablet"
                        },
                        new
                        {
                            Id = 7,
                            Custo = 8.90m,
                            DataInicio = new DateTime(2023, 7, 11, 16, 30, 33, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 5,
                            FuncionariosFK = 4,
                            Observacao = "É preciso mudar os botões"
                        },
                        new
                        {
                            Id = 8,
                            Custo = 50.77m,
                            DataInicio = new DateTime(2023, 7, 9, 15, 0, 12, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 6,
                            FuncionariosFK = 3,
                            Observacao = "É preciso encomendar uma bateria nova"
                        },
                        new
                        {
                            Id = 9,
                            Custo = 10.00m,
                            DataFim = new DateTime(2023, 2, 17, 14, 30, 11, 435, DateTimeKind.Local).AddTicks(8516),
                            DataInicio = new DateTime(2023, 2, 15, 13, 45, 51, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 1,
                            FuncionariosFK = 5,
                            Observacao = "Arranjado"
                        },
                        new
                        {
                            Id = 10,
                            Custo = 20.30m,
                            DataFim = new DateTime(2023, 7, 10, 15, 50, 45, 33, DateTimeKind.Local).AddTicks(24),
                            DataInicio = new DateTime(2023, 7, 12, 14, 25, 20, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 3,
                            FuncionariosFK = 5,
                            Observacao = "Arranjado"
                        },
                        new
                        {
                            Id = 11,
                            Custo = 60.78m,
                            DataFim = new DateTime(2023, 4, 1, 11, 33, 17, 435, DateTimeKind.Local).AddTicks(8516),
                            DataInicio = new DateTime(2023, 3, 30, 9, 50, 50, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 5,
                            FuncionariosFK = 2,
                            Observacao = "Arranjado"
                        },
                        new
                        {
                            Id = 12,
                            Custo = 60.78m,
                            DataFim = new DateTime(2023, 4, 5, 17, 50, 25, 435, DateTimeKind.Local).AddTicks(8516),
                            DataInicio = new DateTime(2023, 4, 4, 10, 30, 34, 435, DateTimeKind.Local).AddTicks(8516),
                            DispositivoFK = 7,
                            FuncionariosFK = 4,
                            Observacao = "Arranjado"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "f",
                            Name = "Funcionario",
                            NormalizedName = "FUNCIONARIO"
                        },
                        new
                        {
                            Id = "c",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1",
                            RoleId = "a"
                        },
                        new
                        {
                            UserId = "a2",
                            RoleId = "a"
                        },
                        new
                        {
                            UserId = "f1",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "f2",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "f3",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "f4",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "f5",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "c1",
                            RoleId = "c"
                        },
                        new
                        {
                            UserId = "c2",
                            RoleId = "c"
                        },
                        new
                        {
                            UserId = "c3",
                            RoleId = "c"
                        },
                        new
                        {
                            UserId = "c4",
                            RoleId = "c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Dispositivos", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Models.Clientes", "Cliente")
                        .WithMany("ListaDipositivos")
                        .HasForeignKey("ClienteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Fotografias", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Models.Dispositivos", "Dispositivo")
                        .WithMany("ListaFotografias")
                        .HasForeignKey("DispositivoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Reparacao", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Models.Dispositivos", "Dispositivo")
                        .WithMany("ListaReparacao")
                        .HasForeignKey("DispositivoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevWeb_Trab_Final.Models.Funcionarios", "Funcionarios")
                        .WithMany("ListaRepara")
                        .HasForeignKey("FuncionariosFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Data.DevWeb_Trab_Final_User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Data.DevWeb_Trab_Final_User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevWeb_Trab_Final.Data.DevWeb_Trab_Final_User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DevWeb_Trab_Final.Data.DevWeb_Trab_Final_User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Clientes", b =>
                {
                    b.Navigation("ListaDipositivos");
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Dispositivos", b =>
                {
                    b.Navigation("ListaFotografias");

                    b.Navigation("ListaReparacao");
                });

            modelBuilder.Entity("DevWeb_Trab_Final.Models.Funcionarios", b =>
                {
                    b.Navigation("ListaRepara");
                });
#pragma warning restore 612, 618
        }
    }
}
